<a href="https://colab.research.google.com/github/DenZhid/DeepLearningLabs/blob/master/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Начальная настройка и входные данные**

**Необходимые импорты**

In [6]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers.core import Activation, Dropout, Dense
from keras.layers import Flatten, LSTM, GRU
from keras.layers import GlobalMaxPooling1D
from keras.models import Model
from keras.layers.embeddings import Embedding
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.layers import Input
from keras.layers.merge import Concatenate
from keras.layers import Bidirectional

import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt


**Массивы данных**

In [7]:
X = np.array([x+1 for x in range(45)])
print(X)
X = X.reshape(15,3,1)
print(X)
Y = list()
for x in X:
    Y.append(x.sum())

Y = np.array(Y)
print(Y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]

 [[13]
  [14]
  [15]]

 [[16]
  [17]
  [18]]

 [[19]
  [20]
  [21]]

 [[22]
  [23]
  [24]]

 [[25]
  [26]
  [27]]

 [[28]
  [29]
  [30]]

 [[31]
  [32]
  [33]]

 [[34]
  [35]
  [36]]

 [[37]
  [38]
  [39]]

 [[40]
  [41]
  [42]]

 [[43]
  [44]
  [45]]]
[  6  15  24  33  42  51  60  69  78  87  96 105 114 123 132]


# **Имплементация GRU нейронной сети**


**Обучение нейронной сети**

In [13]:
model_GRU = Sequential()
model_GRU.add(GRU(50, activation='relu', input_shape=(3, 1)))
model_GRU.add(Dense(1))
model_GRU.compile(optimizer='adam', loss='mse')

history_GRU = model_GRU.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1)

Epoch 1/1000
1/1 [==============================] - 2s 2s/step - loss: 4417.4878 - val_loss: 16489.7598
Epoch 2/1000
1/1 [==============================] - 0s 44ms/step - loss: 4397.8247 - val_loss: 16429.1172
Epoch 3/1000
1/1 [==============================] - 0s 35ms/step - loss: 4378.4878 - val_loss: 16369.3701
Epoch 4/1000
1/1 [==============================] - 0s 36ms/step - loss: 4359.4487 - val_loss: 16310.4297
Epoch 5/1000
1/1 [==============================] - 0s 35ms/step - loss: 4340.6738 - val_loss: 16252.2031
Epoch 6/1000
1/1 [==============================] - 0s 33ms/step - loss: 4322.1382 - val_loss: 16195.1533
Epoch 7/1000
1/1 [==============================] - 0s 34ms/step - loss: 4303.9448 - val_loss: 16138.6562
Epoch 8/1000
1/1 [==============================] - 0s 34ms/step - loss: 4285.9214 - val_loss: 16082.5088
Epoch 9/1000
1/1 [==============================] - 0s 31ms/step - loss: 4268.0278 - val_loss: 16026.5869
Epoch 10/1000
1/1 [=============================

**Проверка на других данны**

In [14]:
test_input = array([50,51,52])
test_input = test_input.reshape((1, 3, 1))
test_output = model_GRU.predict(test_input, verbose=0)
print(test_output)

[[151.78067]]


# **Имплементация LSTM нейронной сети**

**Обучение нейронной сети**

In [10]:
model_LSTM = Sequential()
model_LSTM.add(LSTM(50, activation='relu', input_shape=(3, 1)))
model_LSTM.add(Dense(1))
model_LSTM.compile(optimizer='adam', loss='mse')

history_LSTM = model_LSTM.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1)

Epoch 1/1000
1/1 [==============================] - 1s 1s/step - loss: 4316.7827 - val_loss: 15943.0781
Epoch 2/1000
1/1 [==============================] - 0s 33ms/step - loss: 4286.3608 - val_loss: 15842.4189
Epoch 3/1000
1/1 [==============================] - 0s 34ms/step - loss: 4257.1582 - val_loss: 15746.7510
Epoch 4/1000
1/1 [==============================] - 0s 40ms/step - loss: 4229.1636 - val_loss: 15655.6953
Epoch 5/1000
1/1 [==============================] - 0s 38ms/step - loss: 4202.5254 - val_loss: 15569.4541
Epoch 6/1000
1/1 [==============================] - 0s 34ms/step - loss: 4176.7368 - val_loss: 15486.4971
Epoch 7/1000
1/1 [==============================] - 0s 39ms/step - loss: 4151.6226 - val_loss: 15405.9795
Epoch 8/1000
1/1 [==============================] - 0s 35ms/step - loss: 4127.1138 - val_loss: 15327.3623
Epoch 9/1000
1/1 [==============================] - 0s 32ms/step - loss: 4103.1533 - val_loss: 15250.1826
Epoch 10/1000
1/1 [=============================

**Проверка на других данны**

In [11]:
test_input = array([50,51,52])
test_input = test_input.reshape((1, 3, 1))
test_output = model_LSTM.predict(test_input, verbose=0)
print(test_output)

[[153.49922]]
